name: xmonad-michaeljohnclancy
version: 0.1.0
synopsis: xmonad setting
github: michaeljohnclancy/xmonad
author: michaeljohnclancy
maintainer: s1623705@sms.ed.ac.uk
copyright: © michaeljohnclancy
license: MIT
dependencies:
  - X11
  - base
  - xmonad
  - xmonad-contrib
  - containers
executables:
  xmonad:
    main: xmonad.hs
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -threaded
      - -O2
      - -with-rtsopts=-N4
